### ISSUE TITLE
(Module 2) Add "Debug Exercice" to exercices list in module overview

### ISSUE THREAD

**Issue by michaelsimard93** [norlab-ulaval/percep3d_lessons#33]
Could be nice if the "Debugging a simple ros node" exercise was listed in the module summary. Right now, only the five first exercices are listed. 

<img width="410" alt="Screen Shot 2022-05-09 at 5 16 57 PM" src="https://user-images.githubusercontent.com/40240298/167500037-ded238dd-69b0-4ad8-88b6-d20800529eac.png">

**Comment by pomerlef** [comment]
yes, good catch. It was added recently. We will add the link before next year.

**Comment by WilliamDubois** [comment]
Link was added in the lesson overview.
