### ISSUE TITLE
TP 1 : Surviving in a flat world

### ISSUE THREAD

**Issue by pomerlef** [norlab-ulaval/percep3d_lessons#34]
In `percep3d_students/exercises/assignement_2d/4-assignment_flat_world.ipynb`

There are typos in the function `helper_func.py, the letter 's' is missing in:
- `rigid_tranformation()`
- `scale_tranformation()`

- [x] rename the functions
- [x] refactor the code to avoid errors

This was well spotted by a student of Summer 2022.

**Comment by WilliamDubois** [comment]
Corrections have been made in the exercises and lessons.
