### ISSUE TITLE
no helper_func.py in assignment_lidars folder

### ISSUE THREAD

**Issue by amoreau96** [norlab-ulaval/percep3d_lessons#37]
In the 3-assignment_lidars notebook, the first cell contains:

``` python
%run ../scripts/helper_func.py
path = "{0}/common/scripts/style.py".format(get_root_path())
%run $path
```

but this crashes as the notebook folder does not have a valid ./scripts/ folder nor a helper_func.py file.

Simply commenting the 3 lines above seems to fix the problem and doesn't break anything in the notebook.

**Comment by WilliamDubois** [comment]
This was indeed causing a crash, the helper_func is not needed so I removed the 3 problematic lines.
