### ISSUE TITLE
Typos from V1.0 (2020)

### ISSUE THREAD

**Issue by pomerlef** [norlab-ulaval/percep3d_lessons#4]
Petite faute de frappe dans le module 1 :
![image](https://user-images.githubusercontent.com/502089/83472476-539a0680-a455-11ea-8f11-8b6476d0e55d.png)

- [ ] Je crois que ça devrait être "has" plutôt que "have"

**Comment by DomBaril** [comment]
Primer on virtual machine : 

Something good to know is ... *

![image](https://user-images.githubusercontent.com/35238687/84665230-99db7500-aeed-11ea-8781-8313ef908e09.png)

**Comment by DomBaril** [comment]
Module 2 exercise 1 : 

![image](https://user-images.githubusercontent.com/35238687/84802511-b7ccd680-afce-11ea-9bca-e2e4b91130b7.png)

Last sentence : Contente should be content

**Comment by DomBaril** [comment]
Module 2 lesson 2 : 

![image](https://user-images.githubusercontent.com/35238687/84806056-22801100-afd3-11ea-9eff-17359100ba3f.png)I

Is sortie the right word? Shouldn't it be more like deployment?

**Comment by vdsmax** [comment]
Module 3, exam_6 lesson:

When i launch exam.show_all(), there is a typo at the question number 15 in french:
FR: Quel est la différence entre une rotation une rotation intrinsèque et extrinsèque ?

**Comment by DomBaril** [comment]
Exercises 2e transformations 3D. Exercise A sneaky problem : 

![image](https://user-images.githubusercontent.com/35238687/86923727-68288900-c0fc-11ea-96fa-2a88ff7d2073.png)

"We have a for loop that repeats this operation nb_iter times and **apply** the transformation R to a point cloud shaped as a cube centered around the origin."

Apply should be written applies in my opinion.

**Comment by DomBaril** [comment]
From exam on 3D space : 

![image](https://user-images.githubusercontent.com/35238687/87453178-2605b880-c5d0-11ea-8f25-c0251d9bb490.png)

What is the operator associated with a rotation matrix that define**s** the Special orthogonal group?

**Comment by DomBaril** [comment]
Lie Algebra, first paragraph of approximating trigonometric functions :+1: 

![image](https://user-images.githubusercontent.com/35238687/87788575-91879a00-c80b-11ea-986d-05e001e04aca.png)

I think you meant "I though that my project, which was about controlling a nanosatellite, was doomed until someone **said** that I could **implement** it myself using a Taylor series, which looks like this for the first four none zero terms"

**Comment by DomBaril** [comment]
Module 5, uncertainty, lesson 1. 2.3.1 Example : 

![image](https://user-images.githubusercontent.com/35238687/88552864-95c56b80-cff2-11ea-9b74-cddb059f406d.png)

For example, a Cauchy distribution **h**as no mean, but has a mode.

**Comment by DomBaril** [comment]
Module 5, uncertainty, lesson 2 : 

![image](https://user-images.githubusercontent.com/35238687/88568413-fc548480-d006-11ea-87c3-19218dfa1ecb.png)

"The second explanation, we I find more interesting", "we" could be removed.

**Comment by pomerlef** [comment]
deadlink in `lessons/uncertainty/0-overview.ipynb`:  Go back to the list of modules

**Comment by pomerlef** [comment]
In the exam for ROS and SE(3):

![image](https://user-images.githubusercontent.com/502089/89140125-b91a7a00-d50e-11ea-9ccd-a2d605810be9.png)

-> test **your** connection

![image](https://user-images.githubusercontent.com/502089/89140713-70fc5700-d510-11ea-8d7c-789d9df897bb.png)

-> we will **do** our

**Comment by DomBaril** [comment]
Registration use case 1 : 

![image](https://user-images.githubusercontent.com/35238687/89443273-0fa9d300-d71e-11ea-8bfb-fff37f7d174c.png)

I think the word "suspension" is missing after "differential".

**Comment by pomerlef** [comment]
In lessons/registration/7-exam_registration.ipynb

![image](https://user-images.githubusercontent.com/502089/89848757-f311fe80-db54-11ea-867e-a48d42963b52.png)

->appropriately
In the same section:

internet -> Internet

**Comment by DomBaril** [comment]
Corrected typos
