### ISSUE TITLE
Add computation examples on matrix multiplication VS for loop

### ISSUE THREAD

**Issue by pomerlef** [norlab-ulaval/percep3d_lessons#9]
In `lessons/transformations_2d/3-lesson_rigid.ipynb` add a script that compute the time of moving a point cloud using matrix mult. vs for loop.

Aslo, in Section "2. Combining basic transformations", review that question:
```
\begin{aligned}
\mat{P}' = \mat{R}_2 (\mat{R}_1 \mat{P} + \mat{t}_1 ) + \mat{t}_2
\textcomma
\end{aligned}
```
as it only work for a point, not for matrices.

**Comment by DomBaril** [comment]
Added the computational difference script, not sure what is needed for the equation as I think a pseudo-code with a for loop for every point would work.

**Comment by pomerlef** [comment]
For the equation, there was a mistake. It needs to be 
```
\begin{aligned}
\mat{p}' = \mat{R}_2 (\mat{R}_1 \mat{p} + \mat{t}_1 ) + \mat{t}_2
\textcomma
\end{aligned}
```
With a lowercase `p`. Check the text to make sure it fit the change of equation.

We cannot sum a matrix with a vector: `\mat{P} + \mat{t}`.

**Comment by DomBaril** [comment]
Fixed in next commit.
